content/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # ex: /home/
    path('', views.index, name='index'),


    #path('addcomment/<int:id>', views.addcomment, name='addcomment'),
    # ex: /polls/5/
    #path('<int:question_id>/', views.detail, name='detail'),
]

food/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # ex: /home/
    path('', views.index, name='index'),
    path('addcomment/<int:id>', views.addcomment, name='addcomment'),
    # ex: /polls/5/
    #path('<int:question_id>/', views.detail, name='detail'),
]

home/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # ex: /home/
    path('', views.index, name='index'),

    # ex: /polls/5/
    #path('<int:question_id>/', views.detail, name='detail'),
]

project1/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from home import views
from order import views as orderviews

urlpatterns = [
    path('', include('home.urls')),
    path('hakkimizda/', views.hakkimizda, name='hakkimizda'),
    path('referanslar/', views.referanslar, name='referanslar'),
    path('iletisim/', views.iletisim, name='iletisim'),
    path('home/', include('home.urls')),
    path('food/', include('food.urls')),
    path('user/', include('user.urls')),
    path('order/', include('order.urls')),
    path('content/', include('content.urls')),
    path('content/<int:id>/<slug:slug>/', views.contentdetail, name='contentdetail'),
    path('menu/<int:id>', views.menu, name='menu'),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('category/<int:id>/<slug:slug>/', views.category_products, name='category_products'),
    path('food/<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    path('search/', views.product_search, name='product_search'),
    path('search_auto/', views.search_auto, name='search_auto'),
    path('logout/', views.logout_view, name='logout_view'),
    path('login/', views.login_view, name='login_view'),
    path('signup/', views.signup_view, name='signup_view'),
    path('shopcart/', orderviews.shopcart, name='shopcart'),
    path('sss/', orderviews.faq, name='faq'),



]
if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

content/models.py
from ckeditor.widgets import CKEditorWidget
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.forms import ModelForm
from django.urls import reverse
from django.utils.safestring import mark_safe
from mptt.fields import TreeForeignKey
from mptt.models import MPTTModel
from django.forms import TextInput,FileInput, Select


class Menu(MPTTModel):
    STATUS = (
        ('True', 'Evet'),
        ('False', 'Hayır'),
    )
    parent = TreeForeignKey('self', blank=True, null=True, related_name='children', on_delete=models.CASCADE)
    title = models.CharField(max_length=100, unique=True)
    link = models.CharField(max_length=100, blank=True)
    status = models.CharField(max_length=10, choices=STATUS)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    class MPTTMeta:
        order_insertion_by = ['title']

    def __str__(self):
        full_path = [self.title]
        k = self.parent
        while k is not None:
            full_path.append(k.title)
            k = k.parent
        return ' / '.join(full_path[::-1])


TYPE = (
    ('HEDİYE', 'HEDİYE'),
    ('ETKİNLİK', 'ETKİNLİK'),
    ('KAMPANYA', 'KAMPANYA'),
)

STATUS = (
    ('True', 'Evet'),
    ('False', 'Hayır'),
)


class Content(models.Model):


    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    menu = models.OneToOneField(Menu,null=True, blank=True, on_delete=models.CASCADE) #relation with Menu table
    type = models.CharField(max_length=10, choices=TYPE)
    title = models.CharField(max_length=150)
    keywords = models.CharField(max_length=255, blank=True)
    description = models.CharField(max_length=255, blank=True)
    image = models.ImageField(blank=True, null=True, upload_to='images/')
    detail = RichTextUploadingField()
    slug = models.SlugField(null=False, unique=True)
    status = models.CharField(max_length=10, choices=STATUS)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def image_tag(self): #resmi adminde gösterdik!!
        return mark_safe('<img src="{}" height="50"/>'.format(self.image.url))
    image_tag.short_description = 'Image'

    def get_absolute_url(self): #otomatik slug oluşturduk!!
        return reverse('content_detail', kwargs={'slug': self.slug})



class ContentForm(ModelForm):
    class Meta:
        model = Content
        fields = ['type', 'title', 'slug', 'keywords', 'description', 'image', 'detail']
        widgets = {
            'title'   : TextInput(attrs={'class': 'form-control','placeholder':'title'}),
            'slug': TextInput(attrs={'class': 'form-control', 'placeholder': 'slug'}),
            'keywords': TextInput(attrs={'class': 'form-control', 'placeholder': 'keywords'}),
            'description': TextInput(attrs={'class': 'form-control', 'placeholder': 'description'}),
            'type': Select(attrs={'class': 'form-control', 'placeholder': 'city'}, choices=TYPE),
            'image': FileInput(attrs={'class': 'form-control', 'placeholder': 'image'}),
            'detail' : CKEditorWidget(),

        }


class CImages(models.Model):
    content=models.ForeignKey(Content,on_delete=models.CASCADE)
    title = models.CharField(max_length=50,blank=True)
    image = models.ImageField(blank=True, upload_to='images/')
    def __str__(self):
        return self.title

    def image_tag(self):
        return mark_safe('<img src="{}" height="50"/>'.format(self.image.url))
    image_tag.short_description = 'Image'


class ContentImageForm(ModelForm):
    class Meta:
        model = CImages
        fields = ['title', 'image']

food/models.py
from django.db import models

# Create your models here.
from django.urls import reverse
from django.utils.safestring import mark_safe
from ckeditor_uploader.fields import RichTextUploadingField
from mptt.fields import TreeForeignKey
from mptt.models import MPTTModel
from django.contrib.auth.models import User
from django.forms import ModelForm


class Category(MPTTModel):
    STATUS = (
        ('True', 'Evet'),
        ('False', 'Hayır'),
    )
    title = models.CharField(max_length=100, unique=True)
    keywords = models.CharField(max_length=255, blank=True)
    description = models.CharField(max_length=255, blank=True)
    image = models.ImageField(blank=True, upload_to='images/')
    status = models.CharField(max_length=10, choices=STATUS)
    slug = models.SlugField(null=False, unique=True)
    parent = TreeForeignKey('self', blank=True, null=True, related_name='children', on_delete=models.CASCADE)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        full_path = [self.title]
        k = self.parent
        while k is not None:
            full_path.append(k.title)
            k = k.parent
        return '-> '.join(full_path[::-1])


    class MPTTMeta:
        order_insertion_by = ['title']


    def image_tag(self):
        return mark_safe('<img src="{}" height="50"/>'.format(self.image.url))
    image_tag.short_description = 'Image'


    def get_absolute_url(self): #otomatik slug oluşturuyoruzz
        return reverse('category_detail', kwargs={'slug': self.slug})



class Food(models.Model):
    STATUS = (
        ('True', 'Evet'),
        ('False', 'Hayır'),
    )
    category = models.ForeignKey(Category, on_delete=models.CASCADE) #relation with Category table
    title = models.CharField(max_length=150)
    keywords = models.CharField(max_length=255, blank=True)
    description = models.CharField(max_length=255, blank=True)
    image = models.ImageField(blank=True, upload_to='images/')
    price = models.FloatField()
    amount = models.IntegerField()
    detail = RichTextUploadingField()
    slug = models.SlugField(null=False, unique=True)
    status = models.CharField(max_length=10, choices=STATUS)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def image_tag(self):
        return mark_safe('<img src="{}" height="50"/>'.format(self.image.url))
    image_tag.short_description = 'Image'

    def catimg_tag(self):
        return mark_safe((Category.status))

    def get_absolute_url(self):
        return reverse('product_detail', kwargs={'slug': self.slug})

class Images(models.Model):
    food=models.ForeignKey(Food,on_delete=models.CASCADE)
    title = models.CharField(max_length=50,blank=True)
    image = models.ImageField(blank=True, upload_to='images/')
    def __str__(self):
        return self.title

    def image_tag(self):
        return mark_safe('<img src="{}" height="50"/>'.format(self.image.url))
    image_tag.short_description = 'Image'



class Comment(models.Model):
    STATUS = (
        ('New', 'Yeni'),
        ('True', 'Evet'),
        ('False', 'Hayır'),

    )
    food = models.ForeignKey(Food, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    subject = models.CharField(max_length=50)
    comment = models.TextField(max_length=200, blank=True)
    rate = models.IntegerField(blank=True)
    status = models.CharField(max_length=10, choices=STATUS,default='New')
    ip = models.CharField(blank=True,max_length=20)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.subject


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['subject','comment','rate']

home/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.forms import ModelForm, TextInput, Textarea
from django.utils.safestring import mark_safe


class Setting(models.Model):
    STATUS = (
        ('True', 'Evet'),
        ('False', 'Hayır'),
    )
    title = models.CharField(max_length=150)
    keywords = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    company = models.CharField(max_length=50)
    address = models.CharField(blank=True, max_length=150)
    phone = models.CharField(blank=True, max_length=15)
    fax = models.CharField(blank=True, max_length=15)
    email = models.CharField(blank=True, max_length=50)
    smtpserver = models.CharField(blank=True, max_length=20)
    smtpemail = models.CharField(blank=True, max_length=20)
    smtppassword = models.CharField(blank=True, max_length=10)
    smtpport = models.CharField(blank=True, max_length=5)
    icon = models.ImageField(blank=True, upload_to='images/')
    facebook = models.CharField(blank=True, max_length=50)
    instagram = models.CharField(blank=True, max_length=50)
    twitter = models.CharField(blank=True, max_length=50)
    aboutus = RichTextUploadingField(blank=True)
    contact = RichTextUploadingField(blank=True)
    references = RichTextUploadingField(blank=True)
    status = models.CharField(max_length=10, choices=STATUS)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

class ContactFormMessage(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Read', 'Read'),
        ('Closed', 'Closed'),
    )
    name = models.CharField(blank=True, max_length=20)
    email = models.CharField(blank=True, max_length=50)
    subject = models.CharField(blank=True, max_length=50)
    message = models.CharField(blank=True, max_length=255)
    status = models.CharField(max_length=10, choices=STATUS, default='New')
    ip = models.CharField(blank=True, max_length=20)
    note = models.CharField(blank=True, max_length=100)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

class ContactFormu(ModelForm):
    class Meta:
        model = ContactFormMessage
        fields = ['name', 'email', 'subject', 'message']
        widgets = {
            'name': TextInput(attrs={'class': 'input', 'placeholder':'Name & Surname'}),
            'subject': TextInput(attrs={'class': 'input', 'placeholder': 'Subject'}),
            'email': TextInput(attrs={'class': 'input', 'placeholder': 'Email Adress'}),
            'message': Textarea(attrs={'class': 'input', 'placeholder': 'Your Message', 'rows':'5'}),

        }


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.CharField(blank=True, max_length=20)
    address = models.CharField(blank=True, max_length=150)
    city = models.CharField(blank=True, max_length=20)
    country = models.CharField(blank=True, max_length=20)
    image = models.ImageField(blank=True, upload_to='images/users/')

    def __str__(self):
        return self.user.username

    def user_name(self):
        return self.user.first_name + ' ' +self.user.first_name +'[' +self.user.username + '] '


    def image_tag(self):
        return mark_safe('<img src="{}" height="50"/>'.format(self.image.url))
    image_tag.short_description = 'Image'


class UserProfileForm(ModelForm):
    class Meta:
        model = UserProfile
        fields = ['phone', 'address', 'city', 'country', 'image']


class FAQ(models.Model):
    STATUS = (
        ('True', 'Evet'),
        ('False', 'Hayır'),
    )
    ordernumber= models.IntegerField()
    question = models.CharField(max_length=150)
    answer = models.TextField()
    status = models.CharField(max_length=10, choices=STATUS)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.question

home/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SearchForm(forms.Form):
    query = forms.CharField(label='Search', max_length=100)
    catid = forms.IntegerField()


class SignUpForm(UserCreationForm):
    username = forms.CharField(label='User Name :', max_length=30)
    email = forms.EmailField(label='Email :', max_length=200)
    first_name = forms.CharField(label='First Name :', max_length=100, help_text='First Name')
    last_name = forms.CharField(label='Last Name :', max_length=100, help_text='Last Name')

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'password1', 'password2')

content/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
def index(request):
    return HttpResponse("content")

home/templates/content_detail.html
{% extends "homebase.html" %}

{% block title %} {{content.title}} {{ setting.company }} {% endblock %}
{% block keywords %} {{ setting.keywords }} {% endblock %}
{% block description %} {{ setting.description }} {% endblock %}

{% block head %}
    <link rel='shortcut icon' type='image/x-icon' href='{{setting.icon.url}}' />
{% endblock %}

{% block sidebar %} {% endblock %}

{% block content %}
    <div id="contact-page" class="container">
        <div class="bg">
            <div class="col-sm-12">
                <div class="row">
                     <div class="breadcrumbs">
                            <ol class="breadcrumb">
                                <li><a href="/">Home</a></li>
                                <li class="active"></li>
                            </ol>
                        </div>



                    <img src="{{ content.image.url }}" height="300" width="350" align="left" style="padding: 10px; border-radius: 25px;"><br>

                    <hr>
                    {{content.detail|safe}}
                </div>

                <div class="row">

                    {% for rs in images %}
                        <span><img src="{{ rs.image.url }}" height="200" width="300" alt=""></span>
                    {% endfor %}


                </div><br><br><hr>

            </div>
        </div>
    </div><!--/#contact-page-->
{% endblock %}

home/templates/product_detail.html
{% extends "homebase.html" %}

{% block title %} {{ product.title }} {% endblock %}
{% block keywords %} {{ product.keywords }} {% endblock %}
{% block description %} {{ product.description }} {% endblock %}

{% block head %}
    <link rel='shortcut icon' type='image/x-icon' href='{{setting.icon.url}}' />
{% endblock %}
{% block content %}
    <div id="contact-page" class="container">
        <div class="bg">
            <div class="row">
                <div class="col-sm-12">
                    <div id="gmap" class="contact-map">


                        <div class="breadcrumbs">
                            <ol class="breadcrumb">
                                <li><a href="/">Home</a></li>
                                <li><a href="#">Foods</a></li>
                                <li><a href="/category/{{ product.category_id }}/{{ product.category.slug }}">{{ product.category }}</a></li>
                                <li class="active">{{ product.title }}</li>
                            </ol>
                        </div><!--/breadcrums-->


                        {% load static %}
                        <section>
                            <div class="container">
                                <div class="row">
                                    <div class="col-sm-3">
                                        <div class="left-sidebar">
                                            <h2>Category</h2>
                                            <div class="panel-group category-products" id="accordian"><!--category-productsr-->


                                                <div class="row">
                                                    <div class="col-sm-9">
                                                        <div class="mainmenu pull-left">
                                                            {% load mptt_tags %}
                                                            <ul class="nav navbar-nav collapse navbar-collapse">

                                                                {% recursetree category %}
                                                                    <br><li   {% if not node.is_leaf_node %} class="dropdown" aria-expanded="true" {% endif %}><a href="/category/{{ node.id }}/{{ node.slug }}">{{ node.title }}{% if not node.is_leaf_node %}<i class="fa fa-angle-down"></i>{% endif %}</a>

                                                                    {% if not node.is_leaf_node %}
                                                                        <ul role="menu" class="sub-menu">
                                                                            <li><a href="/category/{{ node.slug }}">{{ children }}</a></li>

                                                                        </ul>
                                                                    {% endif %}
                                                                </li>
                                                                {% endrecursetree %}

                                                            </ul>
                                                        </div>
                                                    </div>
                                                </div>





                                            </div><!--/category-products-->

                                        </div>
                                    </div>

                                    <div class="col-sm-9 padding-right">
                                        <div class="product-details"><!--product-details-->
                                            <div class="col-sm-5">
                                                <div class="view-product">
                                                    <img src="{{ product.image.url }}"  alt="" />
                                                    <h3>ZOOM</h3>
                                                </div>
                                                <div id="similar-product" class="carousel slide" data-ride="carousel">

                                                    <!-- Wrapper for slides -->
                                                    <div class="carousel-inner">

                                                        <div class="item active">
                                                            <a href=""><img src="{{ product.image.url }}"  style="height: 84px" width="84px" alt=""></a>

                                                            {% for rs in images %}
                                                                <a href=""><img src="{{ rs.image.url }}" style="height: 84px" width="84px" alt=""></a>
                                                            {% endfor %}
                                                        </div>


                                                    </div>

                                                    <!-- Controls -->
                                                    <a class="left item-control" href="#similar-product" data-slide="prev">
                                                        <i class="fa fa-angle-left"></i>
                                                    </a>
                                                    <a class="right item-control" href="#similar-product" data-slide="next">
                                                        <i class="fa fa-angle-right"></i>
                                                    </a>
                                                </div>

                                            </div>
                                            <div class="col-sm-7">
                                                <div class="product-information"><!--/product-information-->
                                                    <img src="{% static 'images/product-details/new.jpg' %}" class="newarrival" alt="" />
                                                    <h2>{{ product.title }}</h2>

                                                    <img src="{% static 'images/product-details/rating.png' %}" alt="" />
                                                    <span>
                                                        
									<span>{{ product.price }}₺</span>

                                    <form action="/order/addtocart/{{ product.id }}" method="post">
                                        {% csrf_token %}

									<label>Quantity:</label>
									<input type="number" class="input" name="quantity" min="1" max="{{ product.amount }}" value="1" />
									<button type="submit" class="btn btn-fefault cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</button>
                                        </form>
								</span>

                                                    <p><b>Condition:</b> New</p>

                                                    <a href=""><img src="{% static 'images/product-details/share.png' %}" class="share img-responsive"  alt="" /></a>
                                                </div><!--/product-information-->
                                            </div>
                                        </div><!--/product-details-->

                                        <div class="category-tab shop-details-tab"><!--category-tab-->
                                            <div class="col-sm-12">
                                                <ul class="nav nav-tabs">
                                                    <li><a href="#details" data-toggle="tab">Details</a></li>
                                                    <li class="active"><a href="#reviews" data-toggle="tab">Reviews</a></li>
                                                </ul>
                                            </div>
                                            <div class="tab-content">
                                                <div class="tab-pane fade" id="details" >


                                                    {{product.detail | safe}}
                                                </div>


                                                <div class="tab-pane fade active in" id="reviews" >
                                                    <div class="col-sm-12">

                                                        {% for rs in comments %}
                                                            <ul>
                                                            <li><a href=""><i class="fa fa-user"></i>{{rs.user.first_name}}</a></li>
                                                            <li><a href=""><i class="fa fa-clock-o"></i>{{rs.create_at}}</a></li>


                                                            <div class="rating-area">
                                                                <ul class="ratings">
                                                                    <li>
                                                                        <i class="fa fa-star color{% if rs.rate < 1 %}color{% endif %}"></i>
                                                                        <i class="fa fa-star color{% if rs.rate < 2 %}color{% endif %}"></i>
                                                                        <i class="fa fa-star color{% if rs.rate < 3 %}color{% endif %}"></i>
                                                                        <i class="fa fa-star color{% if rs.rate < 4 %}color{% endif %}"></i>
                                                                        <i class="fa fa-star color{% if rs.rate < 5 %}color{% endif %}"></i>
                                                                    </li>
                                                                </ul>
                                                            </div><!--/rating-area-->


                                                            <h4>{{ rs.subject }}</h4>
                                                            <p>{{ rs.comment }}</p>
                                                            <br>{% endfor %}
                                                        <p><b>Write Your Review</b></p>

                                                        {% if messages %}
                                                            {% for message in messages %}
                                                                <div class="alert alert-{{ message.tags }}" role="alert">
                                                                    {{ message }}
                                                                </div>
                                                            {% endfor %}
                                                        {% endif %}


                                                        <form action="/food/addcomment/{{ product.id }}" method="post">
                                                            {% csrf_token %}
                                                            <span>
											                    <input type="text" class="input" name="subject" id="id_subject" placeholder="Subject"/>

										                    </span>
                                                            <textarea name="comment" class="input" id="id_comment" placeholder="Your review" ></textarea>

                                                            <div class="rating-area">

                                                                <div class="ratings">
                                                                    <p>Please choose yours rate for this food..</p>
                                                                    <input type="radio"   id="star5" name="rate" value="5" /><label for="star5">5</label><br>
                                                                    <input type="radio"  id="star4" name="rate" value="4" /><label for="star4">4</label><br>
                                                                    <input type="radio"  id="star3" name="rate" value="3" /><label for="star3">3</label><br>
                                                                    <input type="radio"  id="star2" name="rate" value="2" /><label for="star2">2</label><br>
                                                                    <input type="radio"  id="star1" name="rate" value="1" /><label for="star1">1</label><br>
                                                                </div><br><br>

                                                             </div>
                                                                {% if user.id is not None %}
                                                                    <button class="btn btn-default pull-right">
                                                                        Submit
                                                                    </button>
                                                                {% else %}
                                                                    Yorum Eklemek için <a href="/login">Login</a>  Olunuz!!
                                                                {% endif %}

                                                        </form>




                                                    </div>

                                                </div>
                                            </div><!--/category-tab-->

                                        </div>
                                    </div>
                        </section>

                    </div>
                </div>
            </div>



            <div class="row">



            </div>
        </div>
    </div><!--/#contact-page-->
{% endblock %}

home/templates/referanslarimiz.html
{% extends "homebase.html" %}

{% block title %} Referanslarımız -{{ setting.company }} {% endblock %}
{% block keywords %} {{ setting.keywords }} {% endblock %}
{% block description %} {{ setting.description }} {% endblock %}

{% block head %}
    <link rel='shortcut icon' type='image/x-icon' href='{{setting.icon.url}}' />
{% endblock %}

{% block sidebar %} {% endblock %}

{% block content %}
    <div id="contact-page" class="container">
        <div class="bg">
            <div class="row">

                 <div class="breadcrumbs">
                            <ol class="breadcrumb">
                                <li><a href="/">Home</a></li>
                                <li class="active">Referanslarımız</li>
                            </ol>
                        </div><!--/breadcrums-->


                {{setting.references | safe}}
            </div>
        </div>
    </div><!--/#contact-page-->
{% endblock %}