food/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # ex: /home/
    path('', views.index, name='index'),
    path('addcomment/<int:id>', views.addcomment, name='addcomment'),
    # ex: /polls/5/
    #path('<int:question_id>/', views.detail, name='detail'),
]

project1/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from home import views
from order import views as orderviews

urlpatterns = [
    path('', include('home.urls')),
    path('hakkimizda/', views.hakkimizda, name='hakkimizda'),
    path('referanslar/', views.referanslar, name='referanslar'),
    path('iletisim/', views.iletisim, name='iletisim'),
    path('home/', include('home.urls')),
    path('food/', include('food.urls')),
    path('user/', include('user.urls')),
    path('order/', include('order.urls')),
    path('content/', include('content.urls')),
    path('content/<int:id>/<slug:slug>/', views.contentdetail, name='contentdetail'),
    path('menu/<int:id>', views.menu, name='menu'),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('category/<int:id>/<slug:slug>/', views.category_products, name='category_products'),
    path('food/<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    path('search/', views.product_search, name='product_search'),
    path('search_auto/', views.search_auto, name='search_auto'),
    path('logout/', views.logout_view, name='logout_view'),
    path('login/', views.login_view, name='login_view'),
    path('signup/', views.signup_view, name='signup_view'),
    path('shopcart/', orderviews.shopcart, name='shopcart'),
    path('sss/', orderviews.faq, name='faq'),



]
if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # ex: /home/
    path('', views.index, name='index'),
    path('update/', views.user_update, name='user_update'),
    path('password/', views.change_password, name='change_password'),
    path('orders/', views.orders, name='orders'),
    path('orderdetail/<int:id>', views.orderdetail, name='orderdetail'),
    path('comments/', views.comments, name='comments'),
    path('deletecomment/<int:id>', views.deletecomment, name='deletecomment'),
    path('addcontent/', views.addcontent, name='addcontent'),
    path('contents/', views.contents, name='contents'),
    path('contentedit/<int:id>', views.contentedit, name='contentedit'),
    path('contentdelete/<int:id>', views.contentdelete, name='contentdelete'),
    path('contentaddimage/<int:id>', views.contentaddimage, name='contentaddimage'),




    #path('addcomment/<int:id>', views.addcomment, name='addcomment'),
    # ex: /polls/5/
    #path('<int:question_id>/', views.detail, name='detail'),
]

food/models.py
from django.db import models

# Create your models here.
from django.urls import reverse
from django.utils.safestring import mark_safe
from ckeditor_uploader.fields import RichTextUploadingField
from mptt.fields import TreeForeignKey
from mptt.models import MPTTModel
from django.contrib.auth.models import User
from django.forms import ModelForm


class Category(MPTTModel):
    STATUS = (
        ('True', 'Evet'),
        ('False', 'Hayır'),
    )
    title = models.CharField(max_length=100, unique=True)
    keywords = models.CharField(max_length=255, blank=True)
    description = models.CharField(max_length=255, blank=True)
    image = models.ImageField(blank=True, upload_to='images/')
    status = models.CharField(max_length=10, choices=STATUS)
    slug = models.SlugField(null=False, unique=True)
    parent = TreeForeignKey('self', blank=True, null=True, related_name='children', on_delete=models.CASCADE)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        full_path = [self.title]
        k = self.parent
        while k is not None:
            full_path.append(k.title)
            k = k.parent
        return '-> '.join(full_path[::-1])


    class MPTTMeta:
        order_insertion_by = ['title']


    def image_tag(self):
        return mark_safe('<img src="{}" height="50"/>'.format(self.image.url))
    image_tag.short_description = 'Image'


    def get_absolute_url(self): #otomatik slug oluşturuyoruzz
        return reverse('category_detail', kwargs={'slug': self.slug})



class Food(models.Model):
    STATUS = (
        ('True', 'Evet'),
        ('False', 'Hayır'),
    )
    category = models.ForeignKey(Category, on_delete=models.CASCADE) #relation with Category table
    title = models.CharField(max_length=150)
    keywords = models.CharField(max_length=255, blank=True)
    description = models.CharField(max_length=255, blank=True)
    image = models.ImageField(blank=True, upload_to='images/')
    price = models.FloatField()
    amount = models.IntegerField()
    detail = RichTextUploadingField()
    slug = models.SlugField(null=False, unique=True)
    status = models.CharField(max_length=10, choices=STATUS)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def image_tag(self):
        return mark_safe('<img src="{}" height="50"/>'.format(self.image.url))
    image_tag.short_description = 'Image'

    def catimg_tag(self):
        return mark_safe((Category.status))

    def get_absolute_url(self):
        return reverse('product_detail', kwargs={'slug': self.slug})

class Images(models.Model):
    food=models.ForeignKey(Food,on_delete=models.CASCADE)
    title = models.CharField(max_length=50,blank=True)
    image = models.ImageField(blank=True, upload_to='images/')
    def __str__(self):
        return self.title

    def image_tag(self):
        return mark_safe('<img src="{}" height="50"/>'.format(self.image.url))
    image_tag.short_description = 'Image'



class Comment(models.Model):
    STATUS = (
        ('New', 'Yeni'),
        ('True', 'Evet'),
        ('False', 'Hayır'),

    )
    food = models.ForeignKey(Food, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    subject = models.CharField(max_length=50)
    comment = models.TextField(max_length=200, blank=True)
    rate = models.IntegerField(blank=True)
    status = models.CharField(max_length=10, choices=STATUS,default='New')
    ip = models.CharField(blank=True,max_length=20)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.subject


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['subject','comment','rate']

user/models.py
from django.db import models

# Create your models here.

user/forms.py
from django import forms
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth.models import User
from django.forms import TextInput,FileInput, Select,EmailInput,PasswordInput
from home.models import UserProfile



class UserUpdateForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name')
        widgets = {


            'username'  : TextInput(attrs={'class':'form-control', 'placeholder':'username'}),
            'email'     : EmailInput(attrs={'class': 'form-control', 'placeholder': 'email'}),
            'first_name': TextInput(attrs={'class': 'form-control', 'placeholder': 'first_name'}),
            'last_name' : TextInput(attrs={'class': 'form-control', 'placeholder': 'last_name'}),


        }
CITY = [
    ('Istanbul','Istanbul'),
    ('Ankara', 'Ankara'),
    ('Izmir','Izmir'),
    ('Bursa','Bursa'),
    ('Edirne','Edirne'),
    ('Kocaeli','Kocaeli'),
]
class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('phone', 'address', 'city', 'country', 'image')
        widgets = {
            'phone'  : TextInput(attrs={'class': 'form-control', 'placeholder': 'phone'}),
            'address': TextInput(attrs={'class': 'form-control', 'placeholder': 'address'}),
            'city'   : Select(attrs={'class': 'form-control', 'placeholder': 'city'},choices=CITY),
            'country': TextInput(attrs={'class': 'form-control', 'placeholder': 'country'}),
            'image'  : FileInput(attrs={'class': 'form-control', 'placeholder': 'image'}),

        }

user/views.py
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.contrib import messages

# Create your views here.
from content.models import Menu, Content, ContentForm, ContentImageForm, CImages
from food.models import Category, Comment
from home.models import UserProfile
from order.models import Order, OrderProduct
from user.forms import UserUpdateForm, ProfileUpdateForm

@login_required(login_url='/login')
def index(request):
    category = Category.objects.all()
    current_user = request.user
    profile = UserProfile.objects.get(user_id=current_user.id)


    context = {
        'category': category,
        'profile': profile
    }

    return render(request, 'user_profile.html', context)

@login_required(login_url='/login')
def user_update(request):
    if request.method == 'POST':
        user_form = UserUpdateForm(request.POST, instance=request.user)

        profile_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.userprofile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, "Hesabınız başarılı bir şekilde güncellenmiştir !")
            return redirect("/user")

    else:
        category = Category.objects.all()
        user_form = UserUpdateForm(instance=request.user)
        profile_form = ProfileUpdateForm(instance=request.user.userprofile)
        context = {
            'category': category,
            'user_form': user_form,
            'profile_form': profile_form,
        }
        return render(request, 'user_update.html', context)

@login_required(login_url='/login')
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            messages.success(request, "Şifreniz başarılı bir şekilde güncellenmiştir !")
            return HttpResponseRedirect("/user")
        else:
            messages.error(request, 'Please correct the error below!<br>'+ str(form.errors))
            return HttpResponseRedirect("/user/password")
    else:
        category = Category.objects.all()
        form = PasswordChangeForm(request.user)
        return render(request, 'change_password.html', {
            'form': form, 'category': category
        })

@login_required(login_url='/login')
def orders(request):
    category = Category.objects.all()
    current_user = request.user
    orders = Order.objects.filter(user_id=current_user.id)
    context = {
        'category': category,
        'orders': orders,
    }
    return render(request, 'user_orders.html', context)

@login_required(login_url='/login')
def orderdetail(request,id):
    category = Category.objects.all()
    current_user = request.user
    order = Order.objects.get(user_id=current_user.id, id=id)
    orderitems = OrderProduct.objects.filter(order_id=id)
    context = {
        'category': category,
        'order': order,
        'orderitems': orderitems,
    }
    return render(request, 'user_order_detail.html', context)

@login_required(login_url='/login')
def comments(request):
    category = Category.objects.all()
    current_user = request.user
    comments = Comment.objects.filter(user_id=current_user.id)
    context = {
        'category': category,
        'comments': comments,

    }
    return render(request, 'user_comments.html', context)

@login_required(login_url='/login')
def deletecomment(request,id):
    current_user = request.user
    Comment.objects.filter(id=id, user_id=current_user.id).delete()
    messages.success(request, 'Your comment deleted success!')

    return HttpResponseRedirect('/user/comments')

@login_required(login_url='/login')
def contents(request):
    category = Category.objects.all()
    menu = Menu.objects.all()
    current_user = request.user
    contents = Content.objects.filter(user_id=current_user.id)
    context = {
        'category': category,
        'menu': menu,
        'contents': contents,

    }

    return render(request, 'user_contents.html', context)

@login_required(login_url='/login')
def addcontent(request):
    if request.method == 'POST':
        form = ContentForm(request.POST, request.FILES)
        if form.is_valid():
            current_user = request.user
            data = Content()
            data.user_id = current_user.id
            data.title = form.cleaned_data['title']
            data.keywords = form.cleaned_data['keywords']
            data.description = form.cleaned_data['description']
            data.image = form.cleaned_data['image']
            data.type = form.cleaned_data['type']
            data.slug = form.cleaned_data['slug']
            data.detail = form.cleaned_data['detail']
            data.status = 'False'
            data.save()
            messages.success(request, 'Your Content Inserted Successfully')
            return HttpResponseRedirect('/user/contents')
        else:
            messages.success(request, 'Content Form Error :' + str(form.errors))
            return HttpResponseRedirect('/user/addcontent')
    else:
        category = Category.objects.all()
        menu = Menu.objects.all()
        form = ContentForm()
        context = {
            'category': category,
            'menu': menu,
            'form': form,

        }
        return render(request, 'user_addcontent.html', context)

@login_required(login_url='/login')
def contentedit(request,id):
    content = Content.objects.get(id=id)
    if request.method == 'POST':
        form = ContentForm(request.POST, request.FILES, instance=content)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your Content Updated Successfully')
            return HttpResponseRedirect('/user/contents')
        else:
            messages.success(request, 'Content Form Error :' + str(form.errors))
            return HttpResponseRedirect('/')
    else:
        category = Category.objects.all()
        menu = Menu.objects.all()
        form = ContentForm(instance=content)
        context = {
            'category': category,
            'menu': menu,
            'form': form,

        }
        return render(request, 'user_addcontent.html', context)

@login_required(login_url='/login')
def contentdelete(request,id):
    current_user = request.user
    Content.objects.filter(id=id, user_id=current_user.id).delete()
    messages.success(request, 'Content deleted..')
    return HttpResponseRedirect('/user/contents')


def contentaddimage(request,id):
    if request.method == 'POST':
        lasturl=request.META.get('HTTP_REFERER')
        form = ContentImageForm(request.POST, request.FILES)
        if form.is_valid():
            data = CImages()
            data.title = form.cleaned_data['title']
            data.content_id = id
            data.image = form.cleaned_data['image']
            data.save()
            messages.success(request, 'Your Image Uploaded Successfully')
            return HttpResponseRedirect(lasturl)
        else:
            messages.success(request, 'Content Form Error :' + str(form.errors))
            return HttpResponseRedirect(lasturl)

    else:
        content = Content.objects.get(id=id)
        images = CImages.objects.filter(content_id=id)
        form = ContentImageForm()
        context = {
            'content': content,
            'images': images,
            'form': form,

        }
        return render(request, 'content_gallery.html', context)

user/templates/change_password.html
{% extends "homebase.html" %}

{% block title %} Profile {{ profile.user_name }} {% endblock %}
{% block keywords %} {{ setting.keywords }} {% endblock %}
{% block description %} {{ setting.description }} {% endblock %}

{% block head %}
    <link rel='shortcut icon' type='image/x-icon' href='{{setting.icon.url}}' />
{% endblock %}

{% block sidebar %} {% endblock %}

{% block content %}
    <div id="contact-page" class="container">
        <div class="bg">
            <div class="row">

                <div class="col-sm-3">
                    <div class="contact-form">
                        <h2 class="title text-center">User Panel</h2>
                        <div class="status alert alert-success" style="display: none"></div>

                        {% include "user_panel.html" %}

                    </div><br>
                </div>


                <div class="col-sm-9">
                    <h2 class="title text-center"> Change Password</h2>

                    {% if messages %}
                        {%  for message in messages %}
                            <div style="color: red; font-size: medium">
                                {{ message|safe }}
                            </div>
                        {% endfor %}
                    {% endif %}



                    <form method="post">
                        {% csrf_token %}

                        {% for field in form %}
                            <p>
                                {{ field.label_tag }}<br>

                                {{ field }}

                                {% if field.help_text %}
                                    <small style="color: purple">{{ field.help_text }}</small>
                                {% endif %}
                                {% for error in field.errors %}
                                    <p style="color: red">{{ error }}</p>
                                {% endfor %}
                            </p>
                        {% endfor %}

                        <button type="submit" class="btn btn-default get">Save Changes</button>
                    </form>

                    <br>
                    <br>
                </div>
            </div>
            <div class="row">
            </div>
        </div>
    </div>
    </div><!--/#contact-page-->
{% endblock %}

user/templates/content_gallery.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Content Gallery</title>
</head>
<p>
<h2>{{ content.title }}</h2>
<hr>
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{message.tags}}" role="alert">
            {{ message|safe }}
        </div>
    {% endfor %}
{% endif %}

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="hidden" name="content_id" id="id_content_id" value="{{ content.id }}">
    <label for="id_title">Title</label>
    <input type="text" name="title" class="input" placeholder="title" maxlength="50" id="id_title"></p>
    <label for="id_image">Image</label>
    <input type="file" name="image" class="input" placeholder="image" accept="image/*" id="id_image"></p>
    <button class="btn btn-warning" type="submit">Upload Image</button>
</form>
<hr>
<h4>Yüklenen Resimler</h4>
{% for rs in images %}
    <img src="{{ rs.image.url }}" height="200" width="350">
{% endfor %}




</body>





</html>

user/templates/user_addcontent.html
{% extends "homebase.html" %}

{% block title %} Add Content {{ profile.user_name }} {% endblock %}
{% block keywords %} {{ setting.keywords }} {% endblock %}
{% block description %} {{ setting.description }} {% endblock %}

{% block head %}
    <link rel='shortcut icon' type='image/x-icon' href='{{setting.icon.url}}' />

    {% load static %}
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
    <script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>

{% endblock %}

{% block content %}
    <div id="contact-page" class="container">
        <div class="bg">
            <div class="row">
                <div class="breadcrumbs">
                    <ol class="breadcrumb">
                        <li><a href="/">Home</a></li>
                        <li class="active">Add Content </li>
                    </ol>
                </div><!--/breadcrums-->


                <div class="col-sm-3">
                    <div class="contact-form">
                        <h2 class="title text-center">User Panel</h2>
                        <div class="status alert alert-success" style="display: none"></div>

                        {% include "user_panel.html" %}


                    </div><br>
                </div>


                <div class="col-sm-9">
                    <h2 class="title text-center"> Add Content</h2>
                    <div class="content">

                        <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            <fieldset class="form-group">

                                {{ form.media}}
                                {{ form.as_p }}

                            </fieldset>
                            <button type="submit" class="btn btn-default get">Save</button>


                        </form>

                    </div>

                    <br>
                    <br>
                </div>


            </div>
            <div class="row">
            </div>
        </div>
    </div>
    </div><!--/#contact-page-->
{% endblock %}

user/templates/user_comments.html
{% extends "homebase.html" %}

{% block title %} Order Comments  {% endblock %}
{% block keywords %} {{ setting.keywords }} {% endblock %}
{% block description %} {{ setting.description }} {% endblock %}

{% block head %}
    <link rel='shortcut icon' type='image/x-icon' href='{{setting.icon.url}}' />
{% endblock %}

{% block content %}
    <div id="contact-page" class="container">
        <div class="bg">
            <div class="row">
                <div class="breadcrumbs">
                    <ol class="breadcrumb">
                        <li><a href="/">Home</a></li>
                        <li class="active">User Comments</li>
                    </ol>
                </div>

                <div class="col-sm-2">
                    <div class="contact-form">
                        <h2 class="title text-center">User Panel</h2>
                        <div class="status alert alert-success" style="display: none"></div>

                        {% include "user_panel.html" %}


                    </div><br>

                </div>


                <div class="col-sm-10">
                    <h2 class="title text-center"> User Order List</h2>


                    <table class="table table-condensed">

                        <tr class="cart_menu">

                            <th class="text-left">Food</th>
                            <th class="text-left">Rate</th>
                            <th class="text-left">Subject</th>
                            <th class="text-left">Comment</th>
                            <th class="text-left">Status</th>
                            <th class="text-left">Date</th>
                            <th class="text-left">Detail</th>
                        </tr>

                        {% for rs in comments %}

                            <tr>

                                <td class="text-left">
                                    <a href="/food/{{ rs.food_id }}/{{ rs.food.slug }}">
                                        <b>{{rs.food.title}}</b>
                                    </a>

                                </td>
                                <td class="text-left">{{rs.rate}}</td>
                                <td class="text-left">{{rs.subject}}</td>
                                <td class="text-left">{{rs.comment}}</td>
                                <td class="text-left">{{rs.status}}</td>
                                <td class="text-left">{{rs.create_at}}</td>

                                <td class="text-left"><a href="/user/deletecomment/{{ rs.id }}" onclick="return confirm('Are you sure want to delete this comment?')" type="submit" class="btn btn-danger">Delete</a></td>

                            </tr>
                        {% endfor %}


                    </table>
                    <br>
                    <br>


                </div>
            </div>
            <div class="row">


            </div>
        </div>
    </div>
    </div><!--/#contact-page-->
{% endblock %}

user/templates/user_contents.html
{% extends "homebase.html" %}

{% block title %} My Contents  {% endblock %}
{% block keywords %} {{ setting.keywords }} {% endblock %}
{% block description %} {{ setting.description }} {% endblock %}

{% block head %}
    <link rel='shortcut icon' type='image/x-icon' href='{{setting.icon.url}}' />
{% endblock %}
{% block content %}
    {% load static %}

    <div id="contact-page" class="container">


        <div class="bg">
            <div class="row">

                <div class="breadcrumbs">
                    <ol class="breadcrumb">
                        <li><a href="/">Home</a></li>
                        <li class="active">User Contents</li>
                    </ol>
                </div>

                <div class="col-sm-2">
                    <div class="contact-form">
                        <h2 class="title text-center">User Panel</h2>
                        <div class="status alert alert-success" style="display: none"></div>

                        {% include "user_panel.html" %}

                    </div><br>

                </div>


                <div class="col-sm-10">
                    <h2 class="title text-center"> User Contents List</h2>

                    <table class="table table-condensed">

                        <tr class="cart_menu">

                        <tr>

                            <th class="text-left">
                                <a href="/user/addcontent" type="submit" class="btn btn-default get">Add Contents</a>

                            </th>
                        </tr>

                        <th class="text-left">Image</th>
                        <th class="text-left">Title</th>
                        <th class="text-left">Type</th>
                        <th class="text-left">Menu</th>
                        <th class="text-center">Gallery</th>
                        <th class="text-left">Status</th>
                        <th class="text-left">Date</th>
                        <th class="text-center">Detail</th>
                        </tr>

                        {% for rs in contents %}

                            <tr>

                                <td class="text-left">
                                    <a href="/content/{{ rs.id }}/{{ rs.slug}}">
                                        <img src="{{ rs.image.url }}" style="height: 30px;">
                                    </a>
                                </td>
                                <td class="text-left">
                                    <a href="/content/{{ rs.id }}/{{ rs.slug}}">
                                        {{rs.title}}
                                    </a>
                                </td>
                                <td class="text-left">{{rs.type}}</td>
                                <td class="text-left">{{rs.menu.title}}</td>

                                <td class="text-center">
                                    <a href="javascript:;" onclick="window.open('/user/contentaddimage/{{ rs.id }}', 'gallery', 'height=600,width=800,top=50,left=150')">
                                        <img style="height: 60px" src="{% static '' %}img/gallery.png"></a>
                                </td>

                                <td class="text-left">{{rs.status}}</td>
                                <td class="text-left">{{rs.create_at}}</td>

                                <td class="text-left"><a class="btn btn-warning" href="/user/contentedit/{{ rs.id }}"> Edit </a> </td>

                                <td class="text-left"><a href="/user/contentdelete/{{ rs.id }}" onclick="return confirm('Are you sure want to delete ?')" type="submit" class="btn btn-danger">Delete</a></td>

                            </tr>
                        {% endfor %}

                    </table>
                    <br>
                    <br>

                </div>
            </div>
            <div class="row">
            </div>
        </div>
    </div>
    </div><!--/#contact-page-->
{% endblock %}

user/templates/user_panel.html
<div class="brands_products"><!--brands_products-->

    <div class="brands-name">
        <ul class="nav nav-pills nav-stacked">
            <li><a href="/user"> <span class="pull-right"></span>User Profile</a></li>
            <li><a href="/user/orders"> <span class="pull-right"></span>My Orders</a></li>
            <li><a href="/user/comments"> <span class="pull-right"></span>My Comments</a></li>
            <li><a href="/user/contents"> <span class="pull-right"></span>My Contents</a></li>
            <li><a href="/logout"> <span class="pull-right"></span>Logout</a></li>

        </ul>
    </div>
</div><!--/brands_products-->

user/templates/user_update.html
{% extends "homebase.html" %}

{% block title %} Profile {{ profile.user_name }} {% endblock %}
{% block keywords %} {{ setting.keywords }} {% endblock %}
{% block description %} {{ setting.description }} {% endblock %}

{% block head %}
    <link rel='shortcut icon' type='image/x-icon' href='{{setting.icon.url}}' />
{% endblock %}

{% block sidebar %} {% endblock %}

{% block content %}
    <div id="contact-page" class="container">


        <div class="bg">
            <div class="row">

                <div class="col-sm-3">
                    <div class="contact-form">
                        <h2 class="title text-center">User Panel</h2>
                        <div class="status alert alert-success" style="display: none"></div>

                        {% include "user_panel.html" %}

                    </div><br>
                </div>

                <div class="col-sm-9">
                    <h2 class="title text-center"> User Information</h2>

                    <div class="content">

                        <div class="media">
                            <img src="{{user.userprofile.image.url}}" style="width: 90px" height="90px" alt="">
                        </div>

                        <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            <fieldset class="form-group">

                                {{ user_form.as_p }}
                                {{ profile_form.as_p }}

                            </fieldset>
                            <button type="submit" class="btn btn-default get">Update</button>


                        </form>

                    </div>

                    <br>
                    <br>

                </div>
            </div>
            <div class="row">
            </div>
        </div>
    </div>
    </div><!--/#contact-page-->
{% endblock %}