food/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # ex: /home/
    path('', views.index, name='index'),
    path('addcomment/<int:id>', views.addcomment, name='addcomment'),
    # ex: /polls/5/
    #path('<int:question_id>/', views.detail, name='detail'),
]

order/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # ex: /home/
    path('', views.index, name='index'),
    path('addtocart/<int:id>', views.addtocart, name='addtocart'),
    path('deletefromcart/<int:id>', views.deletefromcart, name='deletefromcart'),
    path('orderproduct', views.orderproduct, name='orderproduct'),
    # ex: /polls/5/
    #path('<int:question_id>/', views.detail, name='detail'),
]

project1/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from home import views
from order import views as orderviews

urlpatterns = [
    path('', include('home.urls')),
    path('hakkimizda/', views.hakkimizda, name='hakkimizda'),
    path('referanslar/', views.referanslar, name='referanslar'),
    path('iletisim/', views.iletisim, name='iletisim'),
    path('home/', include('home.urls')),
    path('food/', include('food.urls')),
    path('user/', include('user.urls')),
    path('order/', include('order.urls')),
    path('content/', include('content.urls')),
    path('content/<int:id>/<slug:slug>/', views.contentdetail, name='contentdetail'),
    path('menu/<int:id>', views.menu, name='menu'),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('category/<int:id>/<slug:slug>/', views.category_products, name='category_products'),
    path('food/<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    path('search/', views.product_search, name='product_search'),
    path('search_auto/', views.search_auto, name='search_auto'),
    path('logout/', views.logout_view, name='logout_view'),
    path('login/', views.login_view, name='login_view'),
    path('signup/', views.signup_view, name='signup_view'),
    path('shopcart/', orderviews.shopcart, name='shopcart'),
    path('sss/', orderviews.faq, name='faq'),



]
if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.forms import ModelForm

from food.models import Food


class ShopCart(models.Model):

    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    product = models.ForeignKey(Food, on_delete=models.SET_NULL, null=True)
    quantity = models.IntegerField()

    def __str__(self):
        return self.product.title

    @property
    def amount(self):
        return (self.quantity * self.product.price)

    @property
    def price(self):
        return (self.product.price)



class ShopCartForm(ModelForm):
    class Meta:
        model = ShopCart
        fields = ['quantity']


class Order(models.Model):
    STATUS = (
        ('New', 'Yeni'),
        ('Accepted', 'Accepted'),
        ('Preaparing', 'Preaparing'),
        ('Completed', 'Completed'),
        ('Canceled', 'Canceled'),


    )

    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    code = models.CharField(max_length=5, editable=False)
    first_name = models.CharField(max_length=10)
    last_name = models.CharField(max_length=10)
    phone = models.CharField(blank=True, max_length=20)
    address = models.CharField(blank=True, max_length=150)
    city = models.CharField(blank=True, max_length=20)
    country = models.CharField(blank=True, max_length=20)
    total = models.FloatField()
    status = models.CharField(choices=STATUS, max_length=10, default='New')
    ip = models.CharField(blank=True, max_length=20)
    adminnote = models.CharField(blank=True, max_length=100)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.first_name

class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = ['first_name','last_name','address', 'phone', 'city', 'country']


class OrderProduct(models.Model):
    STATUS = (
        ('New', 'Yeni'),
        ('Accepted', 'Accepted'),
        ('Canceled', 'Canceled'),

    )

    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Food, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    price = models.FloatField()
    amount = models.FloatField()
    status = models.CharField(choices=STATUS, max_length=18, default='New')
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.product.title

order/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
from django.utils.crypto import get_random_string

from food.models import Category, Food
from home.models import UserProfile, FAQ
from order.models import ShopCartForm, ShopCart, OrderForm, Order, OrderProduct


def index(request):
    return HttpResponse("order app")

@login_required(login_url='/login')
def addtocart(request,id):
    url = request.META.get('HTTP_REFERER')
    current_user = request.user

    checkproduct = ShopCart.objects.filter(product_id=id)
    if checkproduct:
        control = 1
    else:
        control = 0


    if request.method == 'POST':
        form = ShopCartForm(request.POST)
        if form.is_valid():
            if control==1:
                data = ShopCart.objects.get(product_id=id)
                data.quantity += form.cleaned_data['quantity']
                data.save() #veritabanına kaydeder.
            else: #sepette ürün yoksa.

                data = ShopCart()
                data.user_id = current_user.id
                data.product_id = id
                data.quantity = form.cleaned_data['quantity']
                data.save()
        request.session['cart_items'] = ShopCart.objects.filter(user_id=current_user.id).count()
        messages.success(request,"Ürün başarı ile sepete eklenmiştir. Teşekkürler..")
        return HttpResponseRedirect(url)

    else: #Ürün direkt sepete ekle butonuna basıldıysa bu if calisir
        if control == 1:
            data = ShopCart.objects.get(product_id=id)
            data.quantity += 1
            data.save()

        else:
            data = ShopCart()
            data.user_id = current_user.id
            data.product_id = id
            data.quantity = 1
            data.save()
            request.session['cart_items'] = ShopCart.objects.filter(user_id=current_user.id).count()
            messages.success(request, "Ürün başarı ile sepete eklenmiştir. Teşekkürler..")
            return HttpResponseRedirect(url)

    messages.warning(request,"Ürünü sepete eklemede hata oluştu. Lütfen kontrol ediniz. ")

    return HttpResponseRedirect(url)

@login_required(login_url='/login')
def shopcart(request):
    category = Category.objects.all()
    current_user = request.user
    shopcart = ShopCart.objects.filter(user_id=current_user.id)
    request.session['cart_items'] = ShopCart.objects.filter(user_id=current_user.id).count()

    total=0
    for rs in shopcart:
        total += rs.product.price * rs.quantity  #ürün sayısı ile fiyatını carptık. toplama ekledik.

    context = {'shopcart': shopcart,
               'category': category,
               'total': total,
               }
    return render(request, 'Shopcart_products.html', context)

@login_required(login_url='/login')
def deletefromcart(request,id):      #ürünü sepetten silme
    ShopCart.objects.filter(id=id).delete()

    current_user = request.user
    request.session['cart_items'] = ShopCart.objects.filter(user_id=current_user.id).count()
    messages.success(request, "Ürün sepetten silinmiştir.")
    return HttpResponseRedirect("/shopcart")



@login_required(login_url='/login')
def orderproduct(request):  #siparis edilen urunu kaydediyoruz.
    current_user = request.user
    category = Category.objects.all()
    shopcart = ShopCart.objects.filter(user_id=current_user.id)
    total=0
    for rs in shopcart:
        total += rs.quantity * rs.product.price


    if request.method == 'POST':
        form = OrderForm(request.POST)
        # check whether it's valid:
        if form.is_valid():

            # Send Credit card information to bank and get result
            # If payment accepted continue else send payment error to checkout page

            data = Order()
            data.first_name = form.cleaned_data['first_name'] #get product quantity from form
            data.last_name = form.cleaned_data['last_name']
            data.address = form.cleaned_data['address']
            data.city = form.cleaned_data['city']
            data.phone = form.cleaned_data['phone']
            data.user_id = current_user.id
            data.total = total
            data.ip = request.META.get('REMOTE_ADDR')
            ordercode = get_random_string(5).upper()
            data.code = ordercode
            data.save()

            shopcart = ShopCart.objects.filter(user_id=current_user.id)
            for rs in shopcart:
                detail = OrderProduct()
                detail.order_id     = data.id # Order Id
                detail.product_id   = rs.product_id
                detail.user_id      = current_user.id
                detail.quantity     = rs.quantity
                #  Reduce product Amount  (quantity)
                detail.price = rs.product.price
                detail.amount = rs.amount
                detail.save()

                product = Food.objects.get(id=rs.product_id)
                product.amount -= rs.quantity #urunu stoktan sayısını azalttık
                product.save()

            ShopCart.objects.filter(user_id=current_user.id).delete() # Clear & Delete shopcart
            request.session['cart_items']=0
            messages.success(request, "Your Order has been completed.  Thank You ")
            return render(request, 'Order_Completed.html',{'ordercode':ordercode,'category':category})
        else:
            messages.warning(request, form.errors)
            return HttpResponseRedirect("/order/orderproduct")

    form = OrderForm()
    profile = UserProfile.objects.get(user_id=current_user.id)
    context = {'form': form,
               'category':category,
               'shopcart': shopcart,
               'total': total,
               'profile':profile,
               }
    return render(request, 'Order_Form.html', context)


def faq(request):
    category = Category.objects.all()
    faq=FAQ.objects.all().order_by('ordernumber')
    context = {
               'category': category,
               'faq': faq,

               }
    return render(request, 'faq.html', context)

order/templates/Order_Completed.html
{% extends "homebase.html" %}

{% block title %} Onaylanan Siparişlerim {{ setting.company }} {% endblock %}
{% block keywords %} {{ setting.keywords }} {% endblock %}
{% block description %} {{ setting.description }} {% endblock %}

{% block head %}
    <link rel='shortcut icon' type='image/x-icon' href='{{setting.icon.url}}' />
{% endblock %}
{% block content %}
    <div id="contact-page" class="container">
        <div class="bg">
            <div class="row">

                <div class="breadcrumbs">
                    <ol class="breadcrumb">
                        <li><a href="/">Home</a></li>
                        <li class="active">Order Food</li>
                    </ol>
                </div>


                <div class="col-sm-12">
                    <div id="gmap" class="contact-map">


                        {% if messages %}
                            {%  for message in messages %}
                                <div class="alert alert-{{ message.tags}}" role="alert">
                                    {{ user.first_name }} , {{ message }}
                                </div>

                            {% endfor %}
                        {% endif %}


                    </div>
                </div>
            </div>
            <div class="row">
            </div>
        </div>
    </div><!--/#contact-page-->
{% endblock %}

order/templates/Order_Form.html
{% extends "homebase.html" %}

{% block title %} Order Product {{ setting.company }} {% endblock %}
{% block keywords %} {{ setting.keywords }} {% endblock %}
{% block description %} {{ setting.description }} {% endblock %}

{% block head %}
    <link rel='shortcut icon' type='image/x-icon' href='{{setting.icon.url}}' />
{% endblock %}
{% block content %}
    <div id="contact-page" class="container">
        <div class="bg">
            <div class="row">

                <form action="" method="post">

                    <div class="col-sm-6">
                        <div class="shopper-info">

                            <h2 class="title text-center">Shipping Details</h2>


                            {% csrf_token %}

                            <p><label for="id_first_name">First Name:</label>
                                <input name="first_name" value="{{ user.first_name }}" type="text" class="form-control" placeholder="Display Name"></p>

                            <p><label for="id_last_name">Last Name:</label>
                                <input name="last_name" value="{{ user.last_name }}" type="text" class="form-control" placeholder="Display Name"></p>

                            <p><label for="id_address">Address:</label>
                                <input name="address" value="{{ profile.address }}" type="text" class="form-control" placeholder="Display Name"></p>

                            <p><label for="id_phone">Phone:</label>
                                <input name="phone" value="{{ profile.phone}}" type="text" class="form-control" placeholder="Display Name"></p>

                            <p><label for="id_city">City:</label>
                                <select name="city" class="form-control" id="id_city">
                                    <option value="{{ profile.city }}" selected>{{ profile.city }}</option>
                                    <option value="İstanbul">İstanbul</option>
                                    <option value="Ankara">Ankara</option>
                                    <option value="Bursa">Bursa</option>
                                    <option value="Sakarya">Sakarya</option>
                                    <option value="Karabuk">Karabük</option>
                                </select></p>

                            <p><label for="id_phone">Country:</label>
                                <input name="country" value="{{ profile.country}}" type="text" class="form-control" placeholder="Display Name"></p>




                        </div>
                    </div>


                    <div class="col-sm-6">
                        <div class="shopper-info">

                            <h2 class="title text-center">Payment Information</h2>



                            <p><label for="id_first_name">Total</label>
                                <input name="total" readonly value="₺{{ total }}" type="text" class="form-control" placeholder="Display Name"></p>

                            <p><label for="id_last_name">Credit Card Holder</label>
                                <input name="holder" value="" type="text" class="form-control" ></p>

                            <p><label for="id_address">Credit Card Number</label>
                                <input name="number" value="" type="text" class="form-control" ></p>

                            <p><label for="id_phone">Credit Card Exp Date/Year</label>
                                <input name="ecpdate" value="" type="text" class="form-control" ></p>

                            <p><label for="id_phone">Security Number</label>
                                <input name="secnumber" value="" type="text" class="form-control" ></p>


                            <div class="form-group col-md-12">
                                <input type="submit" name="submit" class="btn btn-primary pull-right" value="Complete Order">
                            </div>

                        </div>
                    </div>

                </form>

                <div class="col-sm-12">
                    <h2 class="title text-center">Shopcart Food List</h2>




                    <div class="table-responsive cart_info">
                        <table class="table table-condensed">
                            <thead>
                            <tr class="cart_menu">
                                <td class="text-center">Item</td>
                                <td class="text-center">Name</td>
                                <td class="text-center">Price</td>
                                <td class="text-center">Quantity</td>
                                <td class="text-center">Total</td>
                                <td class="text-center">Delete Item</td>
                            </tr>
                            </thead>
                            <tbody>

                            {% for rs in shopcart %}

                                <tr>
                                    <td class="text-center">
                                        <a href=""><img src="{{rs.product.image.url}}" style="width: 100px" height="60px" alt=""></a>
                                    </td>
                                    <td class="text-center">
                                        <h4>{{rs.product}}</h4>

                                    </td>
                                    <td class="text-center">
                                        <strong>₺{{ rs.product.price }}</strong><br>
                                    </td>
                                    <td class="text-center">
                                        <div class="cart_quantity_button">
                                            <strong> {{ rs.quantity }}</strong>

                                        </div>
                                    </td>
                                    <td class="text-center">
                                        <h4>{{rs.amount}}</h4>

                                    </td>

                                    <td class="text-center">
                                        <a class="cart_quantity_delete" href="/order/deletefromcart/{{ rs.id }}" onclick="return confirm('Are you sure want to delete this item?')"><i class="fa fa-times"></i></a>
                                    </td>
                                </tr>
                            {% endfor %}



                            <tr>
                                <td colspan="4">&nbsp;</td>
                                <td colspan="2">
                                    <table class="table table-condensed total-result">
                                        <tr>
                                            <td>Cart Sub Total</td>
                                            <td>₺{{total}}</td>
                                        </tr>
                                        <tr class="shipping-cost">
                                            <td>Shipping Cost</td>
                                            <td>Free</td>
                                        </tr>
                                        <tr>
                                            <td>Total</td>
                                            <td><span>₺{{total}}</span></td>
                                        </tr>

                                    </table>
                                </td>
                            </tr>

                            </tbody>

                        </table>
                    </div>
                </div>

            </div>
        </div><!--/#contact-page-->
    </div>
{% endblock %}

order/templates/Shopcart_products.html
{% extends "homebase.html" %}

{% block title %} Shop Cart {{ setting.company }} {% endblock %}
{% block keywords %} {{ categorydata.keywords }} {% endblock %}
{% block description %} {{ categorydata.description }} {% endblock %}

{% block head %}
    <link rel='shortcut icon' type='image/x-icon' href='{{setting.icon.url}}' />
{% endblock %}
{% block content %}
    <div id="contact-page" class="container">

        <div class="breadcrumbs">
            <ol class="breadcrumb">
                <li><a href="/">Home</a></li>
                <li class="active">My Cart</li>
            </ol>
        </div>


        <div class="col-sm-12">
            <h2 class="title text-center">Shopcart Food List</h2>

            <div class="table-responsive cart_info">

                <table class="table table-condensed">
                    <thead>
                    <tr class="cart_menu">
                        <td class="text-center">Item</td>
                        <td class="text-center">Name</td>
                        <td class="text-center">Price</td>
                        <td class="text-center">Quantity</td>
                        <td class="text-center">Total</td>
                        <td class="text-center">Delete Item</td>
                    </tr>
                    </thead>
                    <tbody>

                    {% for rs in shopcart %}

                        <tr>
                            <td class="text-center">
                                <a href=""><img src="{{rs.product.image.url}}" style="width: 100px" height="60px" alt=""></a>
                            </td>
                            <td class="text-center">
                                <h4>{{rs.product}}</h4>

                            </td>
                            <td class="text-center">
                                <strong>₺{{ rs.product.price }}</strong><br>
                            </td>
                            <td class="text-center">
                                <div class="cart_quantity_button">
                                    <strong> {{ rs.quantity }}</strong>

                                </div>
                            </td>
                            <td class="text-center">
                                <h4>{{rs.amount}}</h4>

                            </td>

                            <td class="text-center">
                                <a class="cart_quantity_delete" href="/order/deletefromcart/{{ rs.id }}" onclick="return confirm('Are you sure want to delete this item?')"><i class="fa fa-times"></i></a>
                            </td>
                        </tr>
                    {% endfor %}



                    <tr>
                        <td colspan="4">&nbsp;</td>
                        <td colspan="2">
                            <table class="table table-condensed total-result">
                                <tr>
                                    <td>Cart Sub Total</td>
                                    <td>₺{{total}}</td>
                                </tr>
                                <tr class="shipping-cost">
                                    <td>Shipping Cost</td>
                                    <td>Free</td>
                                </tr>
                                <tr>
                                    <td>Total</td>
                                    <td><span>₺{{total}}</span></td>
                                </tr>

                            </table>
                        </td>
                    </tr>

                    </tbody>

                </table>
            </div>
        </div>
        <div class="form-group col-md-12">
            <a href="/order/orderproduct"><input type="submit" name="submit" class="btn btn-primary pull-right" value="Place Order"></a>
        </div>

        <div class="row">
        </div>
    </div><!--/#contact-page-->
{% endblock %}